package pageobject;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Test;
import pageobject.pagesForAbove.mobile.*;


public class MobileElementsCheckCmsTestAbove {
    private final Logger LOGGER = LogManager.getLogger(this.getClass());
    private BaseFunc baseFunc = new BaseFunc("mobile");

    @Test
    public void MobileElementsCheck() {
        LOGGER.info("This test will be check all elements on each page for mobile version");

        baseFunc.openMobileHomePage();
        MobileHomePage mobileHomePage = new MobileHomePage(baseFunc);
        mobileHomePage.acceptCookies();
        mobileHomePage.logoInHeader();
        mobileHomePage.isTrustpilotLinkAppears();
        mobileHomePage.checkDropDownMenu();
        mobileHomePage.isLogInModalWindowOpens();
        mobileHomePage.loginModalClose();
        mobileHomePage.isSignUpModalWindowOpen();
        mobileHomePage.signUpModalClose();
        mobileHomePage.isCallUsWidgetMobileDisplayed();
        mobileHomePage.isHomePageWelcomeTextAppears();
        mobileHomePage.isTextOneAppears();
        mobileHomePage.isTextTwoAppears();
        mobileHomePage.whyChooseAboveBlockCheck();
        mobileHomePage.reviewBlockCheck();
        mobileHomePage.isInstructionBlockAppears();
        mobileHomePage.isFooterLinksOpen();
        mobileHomePage.isPhoneNumberLinkWorkInFooter();
        mobileHomePage.isEmailLinkWorkInFooter();
        mobileHomePage.isPaymentsDisplayed();
        mobileHomePage.isPaymentMethodImageDisplayed();
        mobileHomePage.isPartnersDisplayed();
        mobileHomePage.isAllRightsTextDisplayed();
        mobileHomePage.isRequestFormAppears();
        mobileHomePage.isElementsInMultiCityFlightRequestFormDisplayed();
        mobileHomePage.openAboutUsPage();
        MobileAboutUsPage mobileAboutUsPage = new MobileAboutUsPage(baseFunc);
        mobileAboutUsPage.logoInHeader();
        mobileAboutUsPage.checkDropDownMenu();
        mobileAboutUsPage.isLogInModalWindowOpens();
        mobileAboutUsPage.loginModalClose();
        mobileAboutUsPage.isSignUpModalWindowOpen();
        mobileAboutUsPage.signUpModalClose();
        mobileAboutUsPage.getTittle();
        mobileAboutUsPage.getMainText();
        mobileAboutUsPage.isFooterLinksOpen();
        mobileAboutUsPage.isPhoneNumberLinkWorkInFooter();
        mobileAboutUsPage.isEmailLinkWorkInFooter();
        mobileAboutUsPage.isPaymentsDisplayed();
        mobileAboutUsPage.isPaymentMethodImageDisplayed();
        mobileAboutUsPage.isPartnersDisplayed();
        mobileAboutUsPage.isAllRightsTextDisplayed();
        mobileAboutUsPage.openBlogPage();
        MobileBlogPage mobileBlogPage = new MobileBlogPage(baseFunc);
        mobileBlogPage.logoInHeader();
        mobileBlogPage.isDropDownMenuOpen();
        mobileBlogPage.isLogInModalWindowOpens();
        mobileBlogPage.loginModalClose();
        mobileBlogPage.isSignUpModalWindowOpen();
        mobileBlogPage.signUpModalClose();
        mobileBlogPage.getTittle();
        mobileBlogPage.isBlogDisplayed();
        mobileBlogPage.isLinksWorksInRandomBlogItems();
        mobileBlogPage.isAllPostRepresentedInBlog();
        mobileBlogPage.isMainBlogPostDisplayed();
        mobileBlogPage.isBlogCardsDisplayed();
        mobileBlogPage.isFooterLinksOpen();
        mobileBlogPage.isPhoneNumberLinkWorkInFooter();
        mobileBlogPage.isEmailLinkWorkInFooter();
        mobileBlogPage.isPaymentsDisplayed();
        mobileBlogPage.isPaymentMethodImageDisplayed();
        mobileBlogPage.isPartnersDisplayed();
        mobileBlogPage.isAllRightsTextDisplayed();
        mobileBlogPage.openTermsOfUsePage();
        MobileTermsOfUsePage mobileTermsOfUsePage = new MobileTermsOfUsePage(baseFunc);
        mobileTermsOfUsePage.logoInHeader();
        mobileTermsOfUsePage.checkDropDownMenu();
        mobileTermsOfUsePage.isLogInModalWindowOpens();
        mobileTermsOfUsePage.loginModalClose();
        mobileTermsOfUsePage.isSignUpModalWindowOpen();
        mobileTermsOfUsePage.signUpModalClose();
        mobileTermsOfUsePage.getTittle();
        mobileTermsOfUsePage.isTextDisplayed();
        mobileTermsOfUsePage.isFooterLinksOpen();
        mobileTermsOfUsePage.isPhoneNumberLinkWorkInFooter();
        mobileTermsOfUsePage.isPhoneNumberLinkWorkInFooter();
        mobileTermsOfUsePage.isEmailLinkWorkInFooter();
        mobileTermsOfUsePage.isPaymentsDisplayed();
        mobileTermsOfUsePage.isPaymentMethodImageDisplayed();
        mobileTermsOfUsePage.isPartnersDisplayed();
        mobileTermsOfUsePage.isAllRightsTextDisplayed();
        mobileTermsOfUsePage.openPrivacyPolicyPage();
        MobilePrivacyPolicyPage mobilePrivacyPolicyPage = new MobilePrivacyPolicyPage(baseFunc);
        mobilePrivacyPolicyPage.logoInHeader();
        mobilePrivacyPolicyPage.checkDropDownMenu();
        mobilePrivacyPolicyPage.isLogInModalWindowOpens();
        mobilePrivacyPolicyPage.loginModalClose();
        mobilePrivacyPolicyPage.isSignUpModalWindowOpen();
        mobilePrivacyPolicyPage.signUpModalClose();
        mobilePrivacyPolicyPage.getTittle();
        mobilePrivacyPolicyPage.isTextDisplayed();
        mobilePrivacyPolicyPage.isLinksWorksInText();
        mobilePrivacyPolicyPage.isFooterLinksOpen();
        mobilePrivacyPolicyPage.isPhoneNumberLinkWorkInFooter();
        mobilePrivacyPolicyPage.isPhoneNumberLinkWorkInFooter();
        mobilePrivacyPolicyPage.isEmailLinkWorkInFooter();
        mobilePrivacyPolicyPage.isPaymentsDisplayed();
        mobilePrivacyPolicyPage.isPaymentMethodImageDisplayed();
        mobilePrivacyPolicyPage.isPartnersDisplayed();
        mobilePrivacyPolicyPage.isAllRightsTextDisplayed();
        mobilePrivacyPolicyPage.openCookiesPolicyPage();
        MobileCookiesPolicyPage mobileCookiesPolicyPage = new MobileCookiesPolicyPage(baseFunc);
        mobileCookiesPolicyPage.logoInHeader();
        mobileCookiesPolicyPage.checkDropDownMenu();
        mobileCookiesPolicyPage.isLogInModalWindowOpens();
        mobileCookiesPolicyPage.loginModalClose();
        mobileCookiesPolicyPage.isSignUpModalWindowOpen();
        mobileCookiesPolicyPage.signUpModalClose();
        mobileCookiesPolicyPage.isTextDisplayed();
        mobileCookiesPolicyPage.isFooterLinksOpen();
        mobileCookiesPolicyPage.isPhoneNumberLinkWorkInFooter();
        mobileCookiesPolicyPage.isPhoneNumberLinkWorkInFooter();
        mobileCookiesPolicyPage.isEmailLinkWorkInFooter();
        mobileCookiesPolicyPage.isPaymentsDisplayed();
        mobileCookiesPolicyPage.isPaymentMethodImageDisplayed();
        mobileCookiesPolicyPage.isPartnersDisplayed();
        mobileCookiesPolicyPage.isAllRightsTextDisplayed();
        mobileCookiesPolicyPage.openContactUsPage();
        MobileContactUsPage mobileContactUsPage = new MobileContactUsPage(baseFunc);
        mobileContactUsPage.checkDropDownMenu();
        mobileContactUsPage.isLogInModalWindowOpens();
        mobileContactUsPage.loginModalClose();
        mobileContactUsPage.isSignUpModalWindowOpen();
        mobileContactUsPage.signUpModalClose();
        mobileContactUsPage.getTittle();
        mobileContactUsPage.isHeadersDisplayed();
        mobileContactUsPage.isPlaceholdersTextDisplayed();
        mobileContactUsPage.isSubmitButtonEnabled();
        mobileContactUsPage.isUsefulInfoBlockDisplayed();
        mobileContactUsPage.isFooterLinksOpen();
        mobileContactUsPage.isPhoneNumberLinkWorkInFooter();
        mobileContactUsPage.isPhoneNumberLinkWorkInFooter();
        mobileContactUsPage.isEmailLinkWorkInFooter();
        mobileContactUsPage.isPaymentsDisplayed();
        mobileContactUsPage.isPaymentMethodImageDisplayed();
        mobileContactUsPage.isPartnersDisplayed();
        mobileContactUsPage.isAllRightsTextDisplayed();
        mobileContactUsPage.manageCookiesPreferencesModalOpen();
        mobileContactUsPage.isModalWindowDisplayedCorrect();
        mobileContactUsPage.manageCookiesPreferencesModalClose();
        mobileContactUsPage.closeBrowser();

    }
}
